Repository EncorePetTeam/petandbe-BE, pull requests merged in 2022-12, with the labels that each got.

#68 #67 Fix Review Service and Reservation entity
  src/main/java/com/encore/petandbe/model/accommodation/reservation/Reservation.java
  src/main/java/com/encore/petandbe/repository/QuerydslReviewListSearchRepository.java
  src/main/java/com/encore/petandbe/repository/ReservationRepository.java
  src/main/java/com/encore/petandbe/repository/ReviewListSearchRepository.java
  src/main/java/com/encore/petandbe/service/accommodation/review/ReviewService.java
  src/test/java/com/encore/petandbe/service/accommodation/review/ReviewServiceTest.java
  src/test/resources/data.sql
Labels: feature

#70 #69 Create Exception handler and Test case
  src/main/java/com/encore/petandbe/exception/BusinessAuthenticityException.java
  src/main/java/com/encore/petandbe/exception/GlobalExceptionHandler.java
  src/main/java/com/encore/petandbe/exception/responses/ExceptionResponse.java
  src/main/java/com/encore/petandbe/infrastructure/BusinessAuthenticityImpl.java
  src/test/java/com/encore/petandbe/exception/GlobalExceptionHandlerTest.java
Labels: feature

#63 #62 Create User-Controller-Test
  src/main/java/com/encore/petandbe/controller/user/user/api/UserController.java
  src/main/java/com/encore/petandbe/controller/user/user/requests/UserUpdateRequest.java
  src/main/java/com/encore/petandbe/controller/user/user/responses/UserDetailsResponse.java
  src/main/java/com/encore/petandbe/controller/user/user/responses/UserIdResponse.java
  src/main/java/com/encore/petandbe/model/user/user/User.java
  src/main/java/com/encore/petandbe/service/user/user/UserService.java
  src/main/java/com/encore/petandbe/service/user/user/dto/UserUpdateDTO.java
  src/main/java/com/encore/petandbe/utils/mapper/UserMapper.java
  src/test/java/com/encore/petandbe/controller/user/user/api/UserControllerTest.java
  src/test/java/com/encore/petandbe/service/user/user/UserServiceTest.java
  src/test/resources/data.sql
Labels: feature

#73 #72 Create Reservation CRUD Controller and Test
  .idea/.name
  .idea/compiler.xml
  .idea/misc.xml
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationController.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/DeleteReservationRequest.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/ReservationRegistrationRequest.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/ReservationUpdatingRequest.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/DeleteReservationResponse.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationDetailsResponse.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationRetrieveResponse.java
  src/main/java/com/encore/petandbe/model/accommodation/reservation/Reservation.java
  src/main/java/com/encore/petandbe/service/accommodation/reservation/ReservationService.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationControllerTest.java
  src/test/java/com/encore/petandbe/service/accommodation/review/ReviewServiceTest.java
  src/test/resources/data.sql
Labels: feature

#84 #47 Create Login Oauth
  .gitignore
  .idea/misc.xml
  build.gradle
  src/main/java/com/encore/petandbe/config/AppConfig.java
  src/main/java/com/encore/petandbe/config/Permission.java
  src/main/java/com/encore/petandbe/controller/oauth/api/OauthController.java
  src/main/java/com/encore/petandbe/controller/oauth/responses/LoginOauthResponse.java
  src/main/java/com/encore/petandbe/controller/oauth/responses/LogoutResponse.java
  src/main/java/com/encore/petandbe/exception/AuthenticationException.java
  src/main/java/com/encore/petandbe/exception/WrongOauthTypeException.java
  src/main/java/com/encore/petandbe/infrastructure/oauth/OauthManager.java
  src/main/java/com/encore/petandbe/infrastructure/oauth/OauthUserInfoDTO.java
  src/main/java/com/encore/petandbe/infrastructure/oauth/RedisManager.java
  src/main/java/com/encore/petandbe/interceptor/PermissionInterceptor.java
  src/main/java/com/encore/petandbe/model/user/user/Role.java
  src/main/java/com/encore/petandbe/repository/UserRepository.java
  src/main/java/com/encore/petandbe/service/jwt/JwtService.java
  src/main/java/com/encore/petandbe/service/jwt/JwtTokenProvider.java
  src/main/java/com/encore/petandbe/service/jwt/JwtTokenService.java
  src/main/java/com/encore/petandbe/service/oauth/OauthCompany.java
  src/main/java/com/encore/petandbe/service/oauth/OauthInformation.java
  src/main/java/com/encore/petandbe/service/oauth/OauthService.java
  src/main/java/com/encore/petandbe/utils/CookieUtil.java
Labels: feature

#79 #77 Create Reservation List
  .idea/sqldialects.xml
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationGetListController.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/ReservationListGetByUserIdRequests.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationListGetByUserIdResponse.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationWithRoomResponse.java
  src/main/java/com/encore/petandbe/model/accommodation/reservation/Reservation.java
  src/main/java/com/encore/petandbe/repository/QuerydslReservationSearchListRepository.java
  src/main/java/com/encore/petandbe/repository/ReservationListSearchRepository.java
  src/main/java/com/encore/petandbe/service/accommodation/reservation/ReservationGetListService.java
  src/main/java/com/encore/petandbe/utils/mapper/ReservationGetListMapper.java
  src/test/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationGetListControllerTest.java
  src/test/java/com/encore/petandbe/service/accommodation/reservation/ReservationGetListServiceTest.java
  src/test/java/com/encore/petandbe/service/accommodation/review/ReviewServiceTest.java
Labels: feature

#86 #85 Fix Bookmark Reservation Review Controller
  src/main/java/com/encore/petandbe/controller/accommodation/bookmark/api/BookmarkController.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationController.java
  src/main/java/com/encore/petandbe/controller/accommodation/review/api/ReviewController.java
  src/main/java/com/encore/petandbe/controller/accommodation/review/api/ReviewGetListController.java
  src/main/java/com/encore/petandbe/service/accommodation/review/ReviewService.java
Labels: fix

#88 #87 Fix User Host Accommodation Controller
  src/main/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationController.java
  src/main/java/com/encore/petandbe/controller/accommodation/accommodation/requests/AccommodationRegistrationRequest.java
  src/main/java/com/encore/petandbe/controller/accommodation/room/api/RoomController.java
  src/main/java/com/encore/petandbe/controller/user/host/api/HostController.java
  src/main/java/com/encore/petandbe/controller/user/host/requests/HostRegistrationRequest.java
  src/main/java/com/encore/petandbe/service/accommodation/accomodation/AccommodationService.java
  src/main/java/com/encore/petandbe/service/user/host/HostService.java
Labels: fix

#89 #85 #87 Fix controller
  src/main/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationController.java
  src/main/java/com/encore/petandbe/controller/accommodation/accommodation/requests/AccommodationRegistrationRequest.java
  src/main/java/com/encore/petandbe/controller/accommodation/bookmark/api/BookmarkController.java
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationController.java
  src/main/java/com/encore/petandbe/controller/accommodation/review/api/ReviewController.java
  src/main/java/com/encore/petandbe/controller/accommodation/review/api/ReviewGetListController.java
  src/main/java/com/encore/petandbe/controller/accommodation/room/api/RoomController.java
  src/main/java/com/encore/petandbe/controller/user/host/api/HostController.java
  src/main/java/com/encore/petandbe/controller/user/host/requests/HostRegistrationRequest.java
  src/main/java/com/encore/petandbe/service/accommodation/accomodation/AccommodationService.java
  src/main/java/com/encore/petandbe/service/accommodation/review/ReviewService.java
  src/main/java/com/encore/petandbe/service/user/host/HostService.java
Labels: fix

#90 #85 #87 Fix Controller Test
  src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationController.java
  src/main/java/com/encore/petandbe/controller/user/user/api/UserController.java
  src/main/java/com/encore/petandbe/interceptor/PermissionInterceptor.java
  src/main/resources/application-common.yml
  src/main/resources/application-secret.yml
  src/main/resources/application.yml
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/bookmark/api/BookmarkControllerIntergrationTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/bookmark/api/BookmarkControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/filtering/api/FilteringControllerIntegrationTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/filtering/api/FilteringControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationGetListControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewControllerIntegrationTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewGetListControllerTest.java
  src/test/java/com/encore/petandbe/controller/accommodation/room/api/RoomControllerTest.java
  src/test/java/com/encore/petandbe/controller/user/host/api/HostControllerTest.java
  src/test/java/com/encore/petandbe/controller/user/user/api/UserControllerTest.java
  src/test/java/com/encore/petandbe/exception/GlobalExceptionHandlerTest.java
  src/test/java/com/encore/petandbe/infrastructure/BusinessAuthenticityImplTest.java
  src/test/java/com/encore/petandbe/service/accommodation/accomodation/AccommodationServiceTest.java
  src/test/java/com/encore/petandbe/service/accommodation/review/ReviewServiceSpringBootTest.java
  src/test/java/com/encore/petandbe/service/accommodation/review/ReviewServiceTest.java
  src/test/java/com/encore/petandbe/service/user/host/HostServiceTest.java
  src/test/resources/application.yml
Labels: fix

#96 #95 Add volumes config on DB service
  .gitignore
  docker-compose-staging.yml
  docker-compose.yml
Labels: ops

#98 #93 Fix Accommodation, Review, Reservation
  app/src/main/java/com/encore/petandbe/controller/accommodation/accommodation/responses/AccommodationRetrievalResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/filtering/api/FilteringController.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/filtering/responses/FilteringAccommodationResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationController.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationGetListController.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/ReservationListGetByUserIdRequests.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/ReservationRegistrationRequest.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/requests/ReservationUpdatingRequest.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationDetailsResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationRetrieveResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/reservation/responses/ReservationWithRoomResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/review/api/ReviewGetListController.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/review/requests/ReviewListGetByAccommodationIdRequests.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/review/responses/ReviewDetailsResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/review/responses/ReviewListGetByAccommodationIdResponse.java
  app/src/main/java/com/encore/petandbe/model/accommodation/accommodation/Accommodation.java
  app/src/main/java/com/encore/petandbe/model/accommodation/reservation/Reservation.java
  app/src/main/java/com/encore/petandbe/repository/QuerydslReservationRetrieveRepository.java
  app/src/main/java/com/encore/petandbe/repository/QuerydslReservationSearchListRepository.java
  app/src/main/java/com/encore/petandbe/repository/QuerydslReviewListSearchRepository.java
  app/src/main/java/com/encore/petandbe/repository/ReviewListSearchRepository.java
  app/src/main/java/com/encore/petandbe/service/accommodation/filtering/FilteringService.java
  app/src/main/java/com/encore/petandbe/service/accommodation/reservation/ReservationGetListService.java
  app/src/main/java/com/encore/petandbe/service/accommodation/reservation/ReservationService.java
  app/src/main/java/com/encore/petandbe/service/accommodation/reservation/dto/ReservationUpdatingDTO.java
  app/src/main/java/com/encore/petandbe/service/accommodation/reservation/dto/ReservationUpdatingdto.java
  app/src/main/java/com/encore/petandbe/service/accommodation/review/ReviewGetListService.java
  app/src/main/java/com/encore/petandbe/service/accommodation/review/ReviewService.java
  app/src/main/java/com/encore/petandbe/utils/mapper/AccommodationMapper.java
  app/src/main/java/com/encore/petandbe/utils/mapper/ReservationMapper.java
  app/src/main/java/com/encore/petandbe/utils/mapper/ReviewGetListMapper.java
  app/src/main/java/com/encore/petandbe/utils/mapper/ReviewMapper.java
  app/src/main/resources/apllication-common.yml
  app/src/test/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/filtering/api/FilteringControllerIntegrationTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/filtering/api/FilteringControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/reservation/api/ReservationGetListControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewControllerIntegrationTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewGetListControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/review/api/ReviewGetListIntergrationTest.java
  app/src/test/java/com/encore/petandbe/service/accommodation/filtering/FilteringServiceTest.java
  app/src/test/java/com/encore/petandbe/service/accommodation/reservation/ReservationGetListServiceTest.java
  app/src/test/java/com/encore/petandbe/service/accommodation/reservation/ReservationServiceTest.java
  app/src/test/java/com/encore/petandbe/service/accommodation/review/ReviewGetListServiceTest.java
  app/src/test/java/com/encore/petandbe/service/accommodation/review/ReviewServiceTest.java
  app/src/test/resources/data.sql
Labels: fix

#99 #97 Apply git-secret to hide secret files
  .gitignore
  .gitsecret/keys/pubring.kbx
  .gitsecret/keys/pubring.kbx~
  .gitsecret/keys/trustdb.gpg
  .gitsecret/paths/mapping.cfg
  README.md
  app/src/main/resources/application-common.yml.secret
  app/src/main/resources/application-secret.yml.secret
  app/src/main/resources/application-security.yml.secret
  common.env
  common.env.secret
Labels: ops

#101 #100 Accommodation image File 추가
  app/build.gradle
  app/src/main/java/com/encore/petandbe/config/AwsConfig.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationController.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/accommodation/requests/AccommodationRegistrationRequest.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/accommodation/responses/AccommodationRetrievalResponse.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/image/file/api/ImageFileController.java
  app/src/main/java/com/encore/petandbe/controller/accommodation/image/file/responses/ImageFileListCreateResponse.java
  app/src/main/java/com/encore/petandbe/exception/ImageFileException.java
  app/src/main/java/com/encore/petandbe/model/accommodation/image/file/File.java
  app/src/main/java/com/encore/petandbe/model/accommodation/image/file/ImageFile.java
  app/src/main/java/com/encore/petandbe/repository/FileRepository.java
  app/src/main/java/com/encore/petandbe/repository/ImageFileRepository.java
  app/src/main/java/com/encore/petandbe/service/accommodation/accomodation/AccommodationService.java
  app/src/main/java/com/encore/petandbe/service/accommodation/image/file/ImageFileService.java
  app/src/main/java/com/encore/petandbe/utils/mapper/AccommodationMapper.java
  app/src/main/java/com/encore/petandbe/utils/validator/MultipartFileValidator.java
  app/src/main/resources/apllication-common.yml
  app/src/test/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationControllerTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/accommodation/api/AccommodationIntergrationTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/bookmark/api/BookmarkControllerIntegrationTest.java
  app/src/test/java/com/encore/petandbe/controller/accommodation/image/file/api/ImageFileControllerTest.java
  app/src/test/java/com/encore/petandbe/service/accommodation/accomodation/AccommodationServiceTest.java
  app/src/test/resources/data.sql
Labels: feature

#111 #109 Update data.sql
  app/src/main/java/com/encore/petandbe/model/accommodation/image/file/ImageFile.java
  app/src/main/java/com/encore/petandbe/service/accommodation/room/RoomService.java
  app/src/test/resources/data.sql
Labels: feature
